"""empty message

Revision ID: a3b296727a68
Revises: 8fefafb36d50
Create Date: 2024-12-12 03:09:08.483291

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3b296727a68"
down_revision: Union[str, None] = "8fefafb36d50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DELETE FROM users")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "formulas",
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("legends", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("users", sa.Column("photo_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "photo_id")
    op.drop_table("formulas")
    # ### end Alembic commands ###
