"""empty message

Revision ID: 68439a6ffc02
Revises: 7d7b6c0b4f35
Create Date: 2024-12-14 05:05:28.288757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68439a6ffc02'
down_revision: Union[str, None] = '7d7b6c0b4f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url', sa.String(), nullable=False))
    op.drop_column('images', 'image_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_uuid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('images', 'url')
    # ### end Alembic commands ###
