"""empty message

Revision ID: 7d7b6c0b4f35
Revises: 5738fa7ce7b8
Create Date: 2024-12-14 05:01:08.322327

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d7b6c0b4f35"
down_revision: Union[str, None] = "5738fa7ce7b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DELETE FROM images")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("image_uuid", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "image_uuid")
    # ### end Alembic commands ###
